const cursos=[
 {id:"soldadura",cat:"industria",nombre:"Soldadura Integral",icono:"🧑‍🏭",imagen:"assets/soldadura-bruner.jpeg",color:"#ff7043",duracion:"3 meses",semanal:"2:30 h",desc:"Dominá las principales técnicas de soldadura utilizadas en el hogar y la industria.",aprendes:["Soldadura por arco eléctrico","Técnica MIG/MAG","Seguridad y uso de herramientas","Práctica sobre trabajos reales"]},
 {id:"muebles",cat:"industria",nombre:"Armado de Muebles",icono:"🪚",color:"#d88b38",duracion:"3 meses",semanal:"2 h",desc:"Aprendé a armar muebles en melamina desde cero y a utilizar las herramientas correctamente.",aprendes:["Lectura y planificación de proyectos","Corte y armado en melamina","Colocación de herrajes","Terminaciones profesionales"]},
 {id:"cerrajeria",cat:"construccion",nombre:"Cerrajería Domiciliaria",icono:"🔐",color:"#536dfe",duracion:"3 meses",semanal:"2 h",desc:"Trabajá con sistemas reales y resolvé los desafíos cotidianos de un cerrajero profesional.",aprendes:["Mecanismos de cerraduras","Diagnóstico de fallas","Apertura y reparación","Herramientas del oficio"]},
 {id:"electricista",cat:"construccion",nombre:"Electricista Domiciliario",icono:"⚡",color:"#f5b700",duracion:"4 meses",semanal:"2 h",desc:"Realizá reparaciones e instalaciones eléctricas domiciliarias respetando las normas vigentes.",aprendes:["Circuitos e instalaciones","Tableros y protecciones","Medición y diagnóstico","Normas de seguridad"]},
 {id:"cat3",cat:"construccion",nombre:"Electricista Habilitado Cat. III",icono:"💡",color:"#ffb300",duracion:"5 meses",semanal:"3 h",desc:"Formate para rendir el examen de ERSeP y completar tu registro oficial como Categoría III.",aprendes:["Proyecto y cálculo eléctrico","Normativa vigente","Mediciones reglamentarias","Preparación para examen ERSeP"]},
 {id:"cnc",cat:"industria",nombre:"Programación CNC",icono:"🤖",color:"#6856d6",duracion:"3 meses",semanal:"2 h",desc:"Desarrollá habilidades en medición, geometría de corte y lenguaje de programación G&M.",aprendes:["Interpretación gráfica","Cálculo cartesiano","Lenguaje G&M","Compensaciones y mecanizado"]},
 {id:"instalacion-aire",cat:"construccion",nombre:"Instalación de Aire Acondicionado",icono:"❄️",color:"#00a7cc",duracion:"2 meses",semanal:"2 h",desc:"Aprendé instalación, normativas, circuitos y uso profesional de manómetros.",aprendes:["Instalación de equipos split","Presión y temperatura","Circuitos eléctricos","Uso de manómetros"]},
 {id:"reparacion-aire",cat:"construccion",nombre:"Reparación de Aires",icono:"🌬️",color:"#1989b6",duracion:"5 meses",semanal:"3 h",desc:"Instalá, mantené y repará equipos split on/off, inverter y piso techo.",aprendes:["Diagnóstico de fallas","Sistemas inverter","Mantenimiento preventivo","Reparación y puesta en marcha"]},
 {id:"refrigeracion",cat:"construccion",nombre:"Refrigeración",icono:"🧰",color:"#27a9e1",duracion:"5 meses",semanal:"2 h",desc:"Diagnosticá y repará heladeras convencionales, No Frost y equipos comerciales.",aprendes:["Ciclo frigorífico","Diagnóstico eléctrico","Sistemas No Frost","Equipos comerciales"]},
 {id:"motos",cat:"automotor",nombre:"Mecánica de Motos",icono:"🏍️",color:"#e44d3a",duracion:"4 meses",semanal:"2:30 h",desc:"Reconocé, desmontá, armá y poné en marcha motores de motocicletas.",aprendes:["Partes y funcionamiento del motor","Desarme y armado","Mantenimiento general","Detección de fallas"]},
 {id:"electricidad-motos",cat:"automotor",nombre:"Electricidad de Motos",icono:"🔋",color:"#e2742f",duracion:"2 meses",semanal:"2 h",desc:"Diagnosticá, medí y repará los sistemas eléctricos de una motocicleta.",aprendes:["Generación y carga","Encendido y arranque","Luces y señalización","Medición con instrumental"]},
 {id:"inyeccion-motos",cat:"automotor",nombre:"Inyección Electrónica de Motos",icono:"🛠️",color:"#c63c36",duracion:"2 meses",semanal:"2 h",desc:"Interpretá señales y datos para diagnosticar fallas con criterio técnico.",aprendes:["Sensores y actuadores","Lectura de parámetros","Diagnóstico electrónico","Resolución de fallas"]},
 {id:"plomeria",cat:"construccion",nombre:"Plomería",icono:"🚰",color:"#1687c9",duracion:"3 meses",semanal:"2 h",desc:"Planificá e instalá sistemas sanitarios, cañerías, griferías y desagües.",aprendes:["Interpretación de planos","Cálculo de cañerías","Instalación de griferías","Desagües cloacales y pluviales"]},
 {id:"microbollos",cat:"automotor",nombre:"Microbollos · Sacabollos",icono:"🚗",color:"#556170",duracion:"6 semanas",semanal:"4 h",desc:"Aprendé reparación sin pintura, presupuestación y claves para iniciar tu emprendimiento.",aprendes:["Tipos y graduación de bollos","Uso de lámpara y herramientas","Técnicas de reparación","Presupuestación del trabajo"]},
 {id:"impresion3d",cat:"creativos",nombre:"Impresión 3D",icono:"🖨️",color:"#7257d9",duracion:"2 meses",semanal:"3 h",desc:"Calibrá, mantené y utilizá impresoras 3D; modelá piezas desde cero.",aprendes:["Partes y tipos de impresoras","Preparación y calibración","Mantenimiento del equipo","Modelado de piezas"]},
 {id:"molderia",cat:"creativos",nombre:"Moldería, Corte y Confección",icono:"🧵",color:"#d6549b",duracion:"5 meses",semanal:"2 h",desc:"Tomá medidas, realizá moldes y confeccioná prendas con terminaciones profesionales.",aprendes:["Toma de medidas","Construcción de moldes","Corte y confección","Terminaciones profesionales"]},
 {id:"lenceria",cat:"creativos",nombre:"Lencería",icono:"✂️",color:"#e05a91",duracion:"2 meses",semanal:"2 h",desc:"Convertí tus ideas en prendas con técnica, precisión y terminaciones cuidadas.",aprendes:["Moldes y progresiones","Telas y elásticos","Técnicas de confección","Terminaciones de lencería"]},
 {id:"trajes-bano",cat:"creativos",nombre:"Trajes de Baño",icono:"🩱",color:"#13a8a0",duracion:"2 meses",semanal:"2 h",desc:"Diseñá y confeccioná trajes de baño trabajando talles, telas y elásticos.",aprendes:["Diseño y proyección de talles","Textiles específicos","Colocación de elásticos","Confección y terminaciones"]}
];
const catalogo=document.querySelector("#catalogo"),modal=document.querySelector("#detail-modal"),modalContent=document.querySelector("#modal-content");
const label={construccion:"Construcción",industria:"Industria",automotor:"Automotor",creativos:"Creativos"};
function visual(c){return c.imagen?`<img class="course-photo" src="${c.imagen}" alt="Práctica del curso de ${c.nombre}">`:`<span class="course-icon">${c.icono}</span>`}
function render(filter="todos"){catalogo.innerHTML=cursos.filter(c=>filter==="todos"||c.cat===filter).map(c=>`<article class="card" style="--accent:${c.color}"><div class="card-visual"><span class="card-tag">${label[c.cat]}</span>${visual(c)}</div><div class="card-body"><h3>${c.nombre}</h3><p class="card-copy">${c.desc}</p><div class="meta"><span>💡 Presencial</span><span>⏱ ${c.duracion}</span></div><button class="card-button" data-course="${c.id}">Ver curso</button></div></article>`).join("");}
function openCourse(id){const c=cursos.find(x=>x.id===id);const media=c.imagen?`<div class="modal-visual has-photo"><img class="course-photo" src="${c.imagen}" alt="Práctica del curso de ${c.nombre}"></div>`:`<div class="modal-visual">${c.icono}</div>`;modalContent.innerHTML=`<div class="modal-grid" style="--accent:${c.color}">${media}<div class="modal-copy"><p class="eyebrow">${label[c.cat]} · Presencial</p><h2>${c.nombre}</h2><p>${c.desc}</p><div class="meta"><span>⏱ Duración: ${c.duracion}</span><span>📅 ${c.semanal} semanales</span></div><h3>¿Qué vas a aprender?</h3><ul>${c.aprendes.map(x=>`<li>${x}</li>`).join("")}</ul><p class="modal-note">Consultá por fechas de inicio, sede disponible, horarios y aranceles.</p><a class="button modal-cta" href="https://brunerinstituto.com/" target="_blank" rel="noreferrer">Quiero más información</a></div></div>`;modal.showModal();}
document.querySelectorAll(".filter").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");render(b.dataset.filter)}));
catalogo.addEventListener("click",e=>{const b=e.target.closest("[data-course]");if(b)openCourse(b.dataset.course)});document.querySelector(".modal-close").onclick=()=>modal.close();modal.addEventListener("click",e=>{if(e.target===modal)modal.close()});render();
