const cursos=[
 {id:"soldadura",cat:"industria",nombre:"Soldadura Integral con prácticas de herrería",icono:"🧑‍🏭",imagen:"assets/soldadura-bruner.jpeg",color:"#ff7043",duracion:"3 meses",semanal:"1 clase semanal de 2:30 h",desc:"Aprendé soldadura desde cero con prácticas crecientes y piezas reales de herrería.",destacado:"Curso netamente práctico",aprendes:["El oficio del soldador, su campo de acción, higiene y seguridad en el taller","Máquinas y herramientas: tipos, usos, manejo, cuidados y mantenimiento","Manejo correcto de la soldadora por arco eléctrico desde cero","Nociones básicas y prácticas de soldadura MIG/MAG","Tipos de electrodos y elección según cada trabajo","Cordones básicos y uniones más utilizadas","Corte, limpieza y preparación correcta de materiales","Técnicas de punteo y presentación de piezas","Terminaciones y desbaste para trabajos prolijos y seguros","Aplicación en piezas simples de herrería","Cómo presupuestar un trabajo de soldadura","Asesoramiento para crear un taller inicial propio"],practica:"Las prácticas son crecientes y culminan con piezas reales de herrería, como parrillas, discos y bancos.",salida:"Al finalizar vas a tener bases reales para comenzar a trabajar, sumarte a un taller como ayudante o dar tus primeros pasos de manera independiente.",ideal:"Ideal para quienes quieren aprender un oficio desde cero con salida laboral inmediata.",sedes:["cordoba","cristo"]},
 {id:"muebles",cat:"industria",nombre:"Diseño y Armado de Muebles MDF",icono:"🪚",color:"#d88b38",duracion:"3 meses",semanal:"2 h semanales",desc:"Diseñá, planificá y construí muebles en MDF y melamina mediante proyectos reales.",destacado:"Proyectos completos reales",aprendes:["Diseño y planificación de muebles en MDF y melamina","Mediciones preliminares y unidades de medida","Ergonomía, usos y funciones del mueble","Colocación y accesorios","Máquinas y herramientas: tipos, manejo, cuidados y mantenimiento","Herrajes y complementos: bisagras, correderas, soportes y tapacantos","Armado de muebles con estantes, puertas y cajoneras","Cómo presupuestar un mueble","Asesoramiento para crear un taller propio"],practica:"Armado práctico de proyectos completos y muebles reales.",sedes:["cordoba","cristo"]},
 {id:"cerrajeria",cat:"construccion",nombre:"Cerrajería Domiciliaria",icono:"🔐",color:"#536dfe",duracion:"3 meses",semanal:"2 h semanales",desc:"Conocé el funcionamiento real de las cerraduras y aprendé aperturas y duplicado de llaves con criterio profesional.",aprendes:["Funcionamiento real de cerraduras domiciliarias","Cerraduras de paleta simple, doble paleta y sistema Yale","Identificación de componentes internos y mecanismos","Apertura de cerraduras trabadas o sin llave","Duplicado de llaves y uso correcto de duplicadoras","Ética profesional, responsabilidad legal y trabajo en domicilios"],salida:"Vas a contar con una base sólida para comenzar a trabajar, sumarte como ayudante o dar tus primeros pasos de manera independiente.",ideal:"Ideal para aprender el oficio desde cero o profesionalizar conocimientos previos.",sedes:["cordoba"]},
 {id:"electricista",cat:"construccion",nombre:"Electricidad Domiciliaria Inicial",icono:"⚡",color:"#f5b700",duracion:"4 meses",semanal:"2 h semanales",desc:"Aprendé de manera práctica a realizar instalaciones eléctricas completas, seguras y ajustadas a la normativa.",aprendes:["Diseño e instalación eléctrica en hogares y comercios","Diagnóstico y solución de problemas eléctricos","Uso profesional de herramientas y equipos de medición","Ley de Seguridad Eléctrica 10.281 y normativa vigente","Proyectos prácticos desde el diseño hasta la instalación final"],salida:"Vas a adquirir habilidades técnicas y teóricas para trabajar en el sector eléctrico y emprender proyectos propios.",sedes:["cordoba","cristo","remedios"]},
 {id:"cat3",cat:"construccion",nombre:"Electricista Habilitado Categoría III",icono:"💡",color:"#ffb300",duracion:"4 meses",semanal:"3 h semanales",desc:"Formate de manera práctica para proyectar instalaciones y rendir el examen de habilitación de ERSeP.",destacado:"Programa basado en el temario oficial de ERSeP",aprendes:["Diseñar, planificar e implementar instalaciones eléctricas seguras y eficientes","Adecuar instalaciones para paneles solares y carga de vehículos eléctricos","Aplicar en profundidad la normativa eléctrica vigente","Interpretar planos domiciliarios y diseñar circuitos eléctricos","Realizar diagramas unifilares y detallar componentes para solicitar el servicio y medidor","Preparación para el examen presencial de Electricista Idóneo Categoría III de ERSeP"],salida:"Formación orientada a cubrir la alta demanda laboral del área eléctrica con seguridad y excelencia técnica.",sedes:["cordoba","cristo"]},
 {id:"cnc",cat:"industria",nombre:"Programación CNC",icono:"🤖",color:"#6856d6",duracion:"3 meses",semanal:"2 h",desc:"Desarrollá habilidades en medición, geometría de corte y lenguaje de programación G&M.",aprendes:["Interpretación gráfica","Cálculo cartesiano","Lenguaje G&M","Compensaciones y mecanizado"],sedes:["cordoba"]},
 {id:"instalacion-aire",cat:"construccion",nombre:"Instalación de Aires Acondicionados",icono:"❄️",color:"#00a7cc",duracion:"2 meses",semanal:"2 h semanales",desc:"Aprendé a instalar equipos split nuevos o usados con herramientas y equipos reales.",aprendes:["Instalación de equipos split nuevos y usados","Máquinas y herramientas: tipos, usos, manejo y mantenimiento","Montaje de unidades interior y exterior","Conexión de caños de cobre","Vacío del sistema, carga de gas y puesta en marcha","Prácticas para garantizar instalaciones seguras y eficientes","Cómo presupuestar una instalación","Asesoramiento para crear un taller propio"],practica:"Práctica guiada con herramientas y equipos reales durante todo el proceso de instalación.",sedes:["cordoba","cristo"]},
 {id:"reparacion-aire",cat:"construccion",nombre:"Mantenimiento, Reparación e Instalación de Aires Acondicionados",icono:"🌬️",color:"#1989b6",duracion:"5 meses",semanal:"3 h semanales",desc:"Instalá, mantené y repará equipos on/off, inverter y piso techo con criterio profesional.",destacado:"Formación integral y práctica",aprendes:["Uso de manifold, bomba de vacío, presurizado, soldadura y mediciones eléctricas","Calor, presión y capacidad frigorífica","Circuitos frío solo y frío/calor, capilar, válvulas y componentes","Vacío, doble vacío, barrido, doble barrido y carga de gas","Diagnóstico de fallas de gas y eléctricas en equipos on/off, inverter y piso techo","Multímetro, pinza amperométrica, capacitores, motores, presostatos y contactores","Placas universales y aplicación en unidades interior y exterior","Instalación de split, inverter y piso techo, con medición de PSI y consumo","Limpieza profunda y mantenimiento de unidades","Manejo seguro de R410A, R22 y R32, recuperación y normas de seguridad"],salida:"Al finalizar vas a poder instalar, mantener y reparar equipos, listo para trabajar y generar ingresos en un oficio de alta demanda.",ideal:"Ideal para aprender un oficio rentable con salida laboral real y práctica guiada.",sedes:["cordoba","cristo"]},
 {id:"refrigeracion",cat:"construccion",nombre:"Refrigeración",icono:"🧰",color:"#27a9e1",duracion:"5 meses",semanal:"2 h",desc:"Diagnosticá y repará heladeras convencionales, No Frost y equipos comerciales.",aprendes:["Ciclo frigorífico","Diagnóstico eléctrico","Sistemas No Frost","Equipos comerciales"]},
 {id:"motos",cat:"automotor",nombre:"Mecánica de Motos",icono:"🏍️",color:"#e44d3a",duracion:"4 meses",semanal:"2:30 h semanales",desc:"Aprendé a identificar, desmontar, armar y poner en marcha motores con criterio técnico y seguridad.",destacado:"Villa Carlos Paz · Sábados",aprendes:["Introducción al oficio, cultura mecánica, rol y valor del mecánico","Herramientas, seguridad y trabajo ordenado en taller","Motores de combustión interna y ciclo Otto","Pistón, cigüeñal, embrague, encendido y caja de cambios","Desmontaje y despiece completo con piezas reales","Diferencias entre motores 2T y 4T","Diagnóstico de fallas frecuentes y soluciones básicas","Reensamblado, puesta a punto, ajustes y carburación","Encendido y puesta en marcha","Refrigeración, lubricación y sistemas eléctricos periféricos"],salida:"Vas a contar con una base sólida para comprender cada sistema, diagnosticar fallas básicas y trabajar con seguridad y responsabilidad.",ideal:"Ideal para transformar la pasión por las motos en un oficio y comenzar a proyectarte dentro del rubro.",sedes:["cristo"]},
 {id:"electricidad-motos",cat:"automotor",nombre:"Electricidad de Motos",icono:"🔋",color:"#e2742f",duracion:"2 meses",semanal:"2 h",desc:"Diagnosticá, medí y repará los sistemas eléctricos de una motocicleta.",aprendes:["Generación y carga","Encendido y arranque","Luces y señalización","Medición con instrumental"],sedes:["remedios"]},
 {id:"inyeccion-motos",cat:"automotor",nombre:"Inyección Electrónica de Motos",icono:"🛠️",color:"#c63c36",duracion:"2 meses",semanal:"2 h semanales",desc:"Interpretá y diagnosticá sistemas de inyección electrónica trabajando con señales reales, mediciones y análisis desde el primer día.",destacado:"Diagnóstico con criterio técnico",aprendes:["Funcionamiento completo del sistema EFI","ECU, sensores y actuadores","TPS, MAP, CKP y sensor de oxígeno","Voltajes, señales y pulsos eléctricos","Tiempos de inyección y lectura de datos","Alimentación, masa y control electrónico","Diagnóstico inicial e interpretación de fallas","Medir, interpretar y resolver con criterio técnico"],sedes:["remedios"]},
 {id:"plomeria",cat:"construccion",nombre:"Plomería e Instalaciones Sanitarias",icono:"🚰",color:"#1687c9",duracion:"4 meses",semanal:"2 h semanales",desc:"Formate como plomero para trabajar en viviendas, comercios y obras mediante práctica en aula-taller.",aprendes:["Lectura de planos y planificación de instalaciones","Montaje de griferías, válvulas y artefactos sanitarios","Redes de agua fría, caliente, cloacales y pluviales","Herramientas, termofusión y bombas presurizadoras","Cámaras sépticas, biodigestores y soluciones ecológicas","Energías renovables y termotanques solares"],practica:"Incluye práctica en aula-taller y un proyecto final supervisado.",salida:"Un oficio concreto y de alta demanda que permite trabajar de manera independiente o sumarse a equipos profesionales.",ideal:"Ideal para aprender desde cero con salida laboral inmediata.",sedes:["cordoba","cristo"]},
 {id:"microbollos",cat:"automotor",nombre:"Microbollos · Sacabollos",icono:"🚗",color:"#556170",duracion:"6 clases",semanal:"Consultar horarios",desc:"Aprendé reparación sin pintura, lectura de reflejos y planificación rentable del trabajo.",aprendes:["Identificación de tipos de bollos, profundidad y complejidad","Comportamiento físico del metal y la pintura automotriz","Herramientas específicas y uso correcto","Lectura de reflejos y uso técnico de la lámpara","Técnica de golpe y figuras básicas de reparación","Presupuestación según tiempo, daño y rentabilidad","Reparación de golpes de choque y planificación","Orden, precisión y cuidado del vehículo","Asesoramiento para crear un taller propio"],sedes:["cordoba"]},
 {id:"impresion3d",cat:"creativos",nombre:"Impresión 3D",icono:"🖨️",color:"#7257d9",duracion:"2 meses",semanal:"3 h semanales",desc:"Manejá impresoras 3D, modelá piezas y resolvé proyectos funcionales desde cero.",destacado:"Curso netamente práctico",aprendes:["Funcionamiento, partes y tipos de impresoras 3D","Preparación, calibración y mantenimiento","Modelado y diseño de piezas desde cero","Preparación de archivos y modelos con software específico","Aplicaciones concretas en distintos rubros y oficios","Impresión 3D como recurso educativo, laboral o emprendedor","Proyectos de fabricación digital con criterio técnico, económico y sustentable"],practica:"Teoría aplicada y práctica progresiva en aula-taller basada en demandas reales de la industria y el mercado tecnológico.",salida:"Formación orientada a emprender o incorporarse a un sector tecnológico en plena expansión.",ideal:"Ideal para aprender desde cero con salida laboral inmediata.",sedes:["cordoba"]},
 {id:"molderia",cat:"creativos",nombre:"Moldería, Corte y Confección",icono:"🧵",color:"#d6549b",duracion:"5 meses",semanal:"2 h semanales",desc:"Aprendé costura, moldería y confección para transformar ideas en prendas y colecciones propias.",aprendes:["Costura a máquina y a mano, puntadas básicas y tipos de tela","Moldes base de falda, corpiño, pantalón y camisa","Transformaciones según tipo de cuerpo, ajustes y entalles","Vestidos, ropa de bebé, camisas, pantalones y saco sastre","Estilo, diseño y creación de una mini colección propia","Cómo presupuestar un trabajo","Asesoramiento para crear un taller propio"],sedes:["cordoba","cristo"]},
 {id:"lenceria",cat:"creativos",nombre:"Lencería",icono:"✂️",color:"#e05a91",duracion:"2 meses",semanal:"2 h",desc:"Convertí tus ideas en prendas con técnica, precisión y terminaciones cuidadas.",aprendes:["Moldes y progresiones","Telas y elásticos","Técnicas de confección","Terminaciones de lencería"]},
 {id:"trajes-bano",cat:"creativos",nombre:"Trajes de Baño",icono:"🩱",color:"#13a8a0",duracion:"2 meses",semanal:"2 h",desc:"Diseñá y confeccioná trajes de baño trabajando talles, telas y elásticos.",aprendes:["Diseño y proyección de talles","Textiles específicos","Colocación de elásticos","Confección y terminaciones"]},
 {id:"facturacion-medica",cat:"salud",nombre:"Secretariado y Facturación Médica",icono:"🧾",color:"#0e9f8f",duracion:"4 meses",semanal:"Consultar horarios",desc:"Aprendé a gestionar documentación, nomencladores y facturación dentro del sistema de salud argentino.",aprendes:["Estructura del sistema de salud argentino","Manejo del Nomenclador Nacional y sus códigos","Lectura, control y validación de órdenes médicas","Facturación de prácticas médicas, bioquímicas, quirúrgicas e internación","Gestión de débitos, reclamos y refacturaciones","Procesos administrativos de hospitales públicos y facturación al Estado","Comunicación, ética y trabajo en equipo"],sedes:["cordoba","remedios"]},
 {id:"auxiliar-farmacia",cat:"salud",nombre:"Auxiliar de Farmacia",icono:"💊",color:"#16a085",duracion:"4 meses",semanal:"Consultar horarios",desc:"Incorporá conocimientos farmacéuticos y administrativos para desempeñarte con responsabilidad en atención al público.",aprendes:["Estructura, funciones y organización del ámbito farmacéutico argentino","Química, biología y anatomía aplicadas a la farmacia","Farmacología, farmacocinética y farmacodinamia","Clasificación y dispensa de medicamentos según principio activo y normativa","Gestión administrativa, facturación y obras sociales","Atención al cliente, ética profesional y comunicación","Cosmetología y dermocosmética"],sedes:["cordoba","remedios"]}
];
const imagenesCursos={muebles:"curso-muebles.webp",cerrajeria:"curso-cerrajeria.webp",electricista:"curso-electricista.webp",cat3:"curso-cat3.webp",cnc:"curso-cnc.webp","instalacion-aire":"curso-instalacion-aire.webp","reparacion-aire":"curso-reparacion-aire.webp",refrigeracion:"curso-refrigeracion.webp",motos:"curso-motos.webp","electricidad-motos":"curso-electricidad-motos.webp","inyeccion-motos":"curso-inyeccion-motos.webp",plomeria:"curso-plomeria.webp",microbollos:"curso-microbollos.webp",impresion3d:"curso-impresion3d.webp",molderia:"curso-molderia.webp",lenceria:"curso-lenceria.webp","trajes-bano":"curso-trajes-bano.webp","facturacion-medica":"curso-facturacion-medica.webp","auxiliar-farmacia":"curso-auxiliar-farmacia.webp"};
cursos.forEach(c=>{if(imagenesCursos[c.id])c.imagen=`assets/${imagenesCursos[c.id]}`});
const sedesInfo={cordoba:{nombre:"Córdoba Capital",detalle:"27 de Abril 991, Córdoba Capital",mapa:"https://maps.app.goo.gl/NYSsUYZKPAvtuDNF9"},cristo:{nombre:"Villa Carlos Paz · Cristo Obrero",detalle:"Florencio Sánchez 394, Villa Carlos Paz · Sábados",mapa:"https://maps.app.goo.gl/yAPhq3r6U9CGdx936"},remedios:{nombre:"Villa Carlos Paz · Remedios de Escalada",detalle:"Av. Estrada y Antártida, Villa Carlos Paz · Jueves",mapa:"https://maps.app.goo.gl/vo9dw7f8dGVgnQFd9"}};
const catalogo=document.querySelector("#catalogo"),modal=document.querySelector("#detail-modal"),modalContent=document.querySelector("#modal-content"),searchInput=document.querySelector("#course-search"),clearSearch=document.querySelector("#clear-search"),resultsSummary=document.querySelector("#results-summary");
const label={construccion:"Construcción",industria:"Industria",automotor:"Automotor",creativos:"Creativos",salud:"Salud"};
function visual(c){return c.imagen?`<img class="course-photo" src="${c.imagen}" alt="Práctica del curso de ${c.nombre}" loading="lazy" decoding="async">`:`<span class="course-icon">${c.icono}</span>`}
function sedeResumen(c){if(!c.sedes)return "Presencial";const capital=c.sedes.includes("cordoba"),vcp=c.sedes.some(x=>x==="cristo"||x==="remedios");return capital&&vcp?"Córdoba · Villa Carlos Paz":capital?"Córdoba Capital":"Villa Carlos Paz"}
let activeFilter="todos",lastTrigger=null;
const normalize=text=>text.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
function render(){const query=normalize(searchInput.value.trim());const visible=cursos.filter(c=>(activeFilter==="todos"||c.cat===activeFilter)&&(!query||normalize([c.nombre,c.desc,...c.aprendes].join(" ")).includes(query)));resultsSummary.innerHTML=visible.length===cursos.length?`<strong>${visible.length}</strong> cursos para elegir`:`<strong>${visible.length}</strong> ${visible.length===1?"curso encontrado":"cursos encontrados"}`;clearSearch.hidden=!query;catalogo.innerHTML=visible.length?visible.map(c=>`<article class="card" style="--accent:${c.color}"><div class="card-visual"><span class="card-tag">${label[c.cat]}</span>${visual(c)}</div><div class="card-body">${c.destacado?`<span class="card-highlight">${c.destacado}</span>`:""}<h3>${c.nombre}</h3><p class="card-copy">${c.desc}</p><div class="meta"><span>📍 ${sedeResumen(c)}</span><span>⏱ ${c.duracion}</span></div><button class="card-button" data-course="${c.id}" aria-label="Ver programa de ${c.nombre}">Ver programa <span aria-hidden="true">→</span></button></div></article>`).join(""):`<div class="empty-state"><span aria-hidden="true">⌕</span><h3>No encontramos ese curso</h3><p>Probá con otra palabra o quitá los filtros.</p><button type="button" id="reset-search">Ver todos los cursos</button></div>`;}
function openCourse(id,trigger){const c=cursos.find(x=>x.id===id);lastTrigger=trigger;const media=c.imagen?`<div class="modal-visual has-photo"><img class="course-photo" src="${c.imagen}" alt="Práctica del curso de ${c.nombre}"></div>`:`<div class="modal-visual">${c.icono}</div>`;const practica=c.practica?`<section class="course-detail"><span class="detail-kicker">Aprender haciendo</span><h3>Práctica real</h3><p>${c.practica}</p></section>`:"";const salida=c.salida||c.ideal?`<section class="course-detail"><span class="detail-kicker">Tu próximo paso</span><h3>Salida laboral</h3>${c.salida?`<p>${c.salida}</p>`:""}${c.ideal?`<p><strong>${c.ideal}</strong></p>`:""}</section>`:"";const sedes=c.sedes?`<section class="course-detail venues"><span class="detail-kicker">Dónde cursar</span><h3>Sedes</h3>${c.sedes.map(id=>{const s=sedesInfo[id];return `<a class="venue-link" href="${s.mapa}" target="_blank" rel="noreferrer"><strong>${s.nombre}</strong><span>${s.detalle}</span><small>Ver en Google Maps ↗</small></a>`}).join("")}</section>`:"";modalContent.innerHTML=`<div class="modal-grid" style="--accent:${c.color}">${media}<div class="modal-copy"><div class="modal-scroll"><header class="course-header"><p class="eyebrow">${label[c.cat]} · Presencial</p><h2>${c.nombre}</h2>${c.destacado?`<span class="course-highlight">${c.destacado}</span>`:""}<p class="modal-intro">${c.desc}</p><div class="meta"><span>⏱ Duración: ${c.duracion}</span><span>📅 ${c.semanal}</span></div></header><details class="course-program" open><summary>Qué vas a aprender <span>${c.aprendes.length} temas</span></summary><ul>${c.aprendes.map(x=>`<li>${x}</li>`).join("")}</ul></details>${practica}${salida}${sedes}<p class="modal-note">Consultá por fechas de inicio, horarios, vacantes y aranceles.</p></div><div class="modal-actions"><button class="button modal-cta" type="button" data-lead-course="${c.id}">Quiero más información <span>→</span></button></div></div></div>`;document.body.classList.add("modal-open");modal.showModal();document.querySelector(".modal-close").focus();}
function closeModal(){modal.close();}
document.querySelectorAll(".filter").forEach(b=>b.addEventListener("click",()=>{activeFilter=b.dataset.filter;document.querySelectorAll(".filter").forEach(x=>{const active=x===b;x.classList.toggle("active",active);x.setAttribute("aria-pressed",active)});render()}));
searchInput.addEventListener("input",render);clearSearch.addEventListener("click",()=>{searchInput.value="";searchInput.focus();render()});catalogo.addEventListener("click",e=>{const reset=e.target.closest("#reset-search");if(reset){searchInput.value="";activeFilter="todos";document.querySelectorAll(".filter").forEach(x=>{const active=x.dataset.filter==="todos";x.classList.toggle("active",active);x.setAttribute("aria-pressed",active)});render();return}const b=e.target.closest("[data-course]");if(b)openCourse(b.dataset.course,b)});document.querySelector(".modal-close").onclick=closeModal;modal.addEventListener("click",e=>{if(e.target===modal)closeModal()});modal.addEventListener("close",()=>{document.body.classList.remove("modal-open");lastTrigger?.focus()});document.addEventListener("keydown",e=>{if(e.key==="/"&&!modal.open&&document.activeElement!==searchInput){e.preventDefault();searchInput.focus()}});render();

const LEAD_API_URL="https://script.google.com/macros/s/AKfycbyhKiGC0ZzG2KpOc-TRoOih2qXUTsG2ckWi98Blyc1j0Fma_R0ec5QcAoysElUBvCo/exec";
const leadModal=document.querySelector("#lead-modal"),leadForm=document.querySelector("#lead-form"),leadCourse=document.querySelector("#lead-course"),leadSite=document.querySelector("#lead-site"),leadFeedback=document.querySelector("#lead-feedback"),leadInstagram=document.querySelector("#lead-instagram");
leadCourse.innerHTML=`<option value="">Elegí un curso</option>${[...cursos].sort((a,b)=>a.nombre.localeCompare(b.nombre,"es")).map(c=>`<option value="${c.id}">${c.nombre}</option>`).join("")}`;
function updateLeadSites(){const c=cursos.find(x=>x.id===leadCourse.value),ids=c?.sedes||Object.keys(sedesInfo);leadSite.innerHTML=`<option value="">Elegí una sede</option>${ids.map(id=>`<option value="${sedesInfo[id].nombre}">${sedesInfo[id].nombre}</option>`).join("")}`;if(ids.length===1)leadSite.value=sedesInfo[ids[0]].nombre;}
function openLead(courseId="",trigger=null){lastTrigger=trigger||document.activeElement;if(modal.open)modal.close();leadForm.reset();leadForm.querySelectorAll("input:not(.lead-honeypot),select").forEach(x=>x.disabled=false);const button=leadForm.querySelector(".lead-submit");button.hidden=false;button.disabled=false;button.innerHTML="Solicitar información <span>→</span>";leadFeedback.textContent="";leadFeedback.className="lead-feedback";leadInstagram.hidden=true;leadCourse.value=courseId;updateLeadSites();document.body.classList.add("modal-open");leadModal.showModal();setTimeout(()=>document.querySelector("#lead-name").focus(),0);}
function closeLead(){leadModal.close();}
document.addEventListener("click",e=>{const cta=e.target.closest("[data-lead-course]");if(cta)openLead(cta.dataset.leadCourse,cta);const generic=e.target.closest(".contact-open");if(generic)openLead("",generic)});
leadCourse.addEventListener("change",updateLeadSites);document.querySelector(".lead-close").addEventListener("click",closeLead);leadModal.addEventListener("click",e=>{if(e.target===leadModal)closeLead()});leadModal.addEventListener("close",()=>{document.body.classList.remove("modal-open");lastTrigger?.focus()});
leadForm.addEventListener("submit",async e=>{e.preventDefault();if(!leadForm.reportValidity())return;const button=leadForm.querySelector(".lead-submit"),fields=leadForm.querySelectorAll("input:not(.lead-honeypot),select"),selected=cursos.find(x=>x.id===leadCourse.value),data=Object.fromEntries(new FormData(leadForm));const payload={action:"createLandingLead",nombre:data.nombre,telefono:data.telefono,curso:selected?.nombre||data.curso,cursoId:data.curso,sede:data.sede,origen:data.origen,website:data.website||"",pagina:location.href};button.disabled=true;button.innerHTML="¡Listo! Estamos enviándola <span>✓</span>";leadFeedback.textContent="Podés cerrar esta ventana. La consulta se guarda en segundo plano.";leadFeedback.className="lead-feedback success";fields.forEach(x=>x.disabled=true);try{const response=await fetch(LEAD_API_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(payload),keepalive:true});const result=await response.json();if(!result.ok)throw Error(result.error||"No pudimos registrar la consulta.");leadFeedback.textContent="¡Gracias! Tu consulta fue enviada. Una asesora se comunicará con vos.";button.hidden=true;leadInstagram.hidden=false;}catch(error){leadFeedback.textContent="No pudimos enviar la consulta. Revisá tu conexión e intentá nuevamente.";leadFeedback.className="lead-feedback error";leadInstagram.hidden=true;fields.forEach(x=>x.disabled=false);button.disabled=false;button.innerHTML="Volver a intentar <span>→</span>";}});

const whatsappWidget=document.querySelector("#whatsapp-widget"),whatsappBubble=document.querySelector("#whatsapp-bubble"),whatsappPanel=document.querySelector("#whatsapp-form"),whatsappCourse=document.querySelector("#whatsapp-course"),whatsappMessage=document.querySelector("#whatsapp-message");
whatsappCourse.innerHTML+= [...cursos].sort((a,b)=>a.nombre.localeCompare(b.nombre,"es")).map(c=>`<option value="${c.id}">${c.nombre}</option>`).join("");
function toggleWhatsApp(show){whatsappPanel.hidden=!show;whatsappBubble.setAttribute("aria-expanded",show);if(show)setTimeout(()=>whatsappCourse.focus(),0)}
whatsappBubble.addEventListener("click",()=>toggleWhatsApp(whatsappPanel.hidden));
document.querySelector(".whatsapp-close").addEventListener("click",()=>toggleWhatsApp(false));
document.addEventListener("click",e=>{if(!whatsappPanel.hidden&&!whatsappWidget.contains(e.target))toggleWhatsApp(false)});
document.addEventListener("keydown",e=>{if(e.key==="Escape"&&!whatsappPanel.hidden)toggleWhatsApp(false)});
whatsappPanel.addEventListener("submit",e=>{e.preventDefault();if(!whatsappPanel.reportValidity())return;const course=cursos.find(c=>c.id===whatsappCourse.value),extra=whatsappMessage.value.trim(),message=["🎓 *CONSULTA DESDE LA WEB DE CURSOS BRUNER*",`Curso: *${course?.nombre||"Sin especificar"}*`,extra?`Consulta: ${extra}`:"Hola, quisiera recibir información sobre este curso.","Origen: Landing pública Bruner"].join("\n");window.open(`https://wa.me/5493516231603?text=${encodeURIComponent(message)}`,"_blank","noopener,noreferrer")});
